jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.dialect=org.hibernate.dialect.Oracle10gDialect
jdbc.databaseurl=jdbc:oracle:thin:@ar3in222.groupe.generali.fr:1521:INSMUTI1
jdbc.username=UEPSNOVI0
jdbc.password=UEPSNOVI9
